title: 'Fundación Grupo Social - Una semilla de cambio'
description: 'Fundación Grupo Social es una organización que acompaña con programas de desarrollo social a las poblaciones menos favorecidas en distintos territorios del país; y al mismo tiempo es la dueña de un sólido grupo empresarial dedicado a servirle a la sociedad.'
logo: settings/January2022/pzDmoGmBa7Lz16mXJrXf.png
footer_direction: 'Calle 72 N° 10 – 71'
footer_telephone: '( 571 ) – 5953810 ext 15396'
receive_email: ''
mail_from: contactenos@fundaciongruposocial.co
google_analytics_tracking_id: UA-141013758-1
google_tag_manager: ''
google_tag_manager_noscript: ''
recaptcha_site_key: ''
recaptcha_secret_key: ''
